config/routes.rb
Rails.application.routes.draw do

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'

  get 'spots/:id/show_map', to: 'spots#show_map', as: 'spots/show_map'

  get 'spots/map', to: 'spots#map'
  get 'trees/map', to: 'trees#map'
  get 'spots/map_test', to: 'spots#map_test'
  get 'spots/geoloc', to: 'spots#geoloc'

  resources :spots, :trees, :taxons
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spot.rb
class Spot < ApplicationRecord
  has_many :trees
  # belongs_to :user

  # Methods
  # count the different number of taxa of a spot
  def taxa_count()
    # list of taxa of each tree of the spot
    taxa_tab = []
    trees.each do |tree|
      taxa_tab << tree.taxon.common_noun
    end
    # calculation of the total taxa without duplication
    tot = taxa_tab.uniq.length
    return tot
  end

  # create array with different taxa of a spot
  def taxa_array()
    # list of taxa of each tree of the spot
    taxa_tab = []
    trees.each do |tree|
      taxa_tab << tree.taxon.common_noun
    end
    # taxa tab without duplication
    taxa_tab.uniq!
    return taxa_tab
  end
end

app/models/taxon.rb
class Taxon < ApplicationRecord
  has_many :trees
end

app/models/tree.rb
class Tree < ApplicationRecord
  belongs_to :spot
  belongs_to :taxon
end

app/models/user.rb
class User < ApplicationRecord
  # has_many :spots
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @spots = Spot.all
    @trees = Tree.all
    @taxons = Taxon.all
  end

end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController

  def new
    @spot = Spot.new
  end

  def index
    @spots = Spot.all
  end

  def create
    spot = Spot.new(post_params)
    if spot.valid?
      spot.save
      redirect_to spot_path(spot.id), success: "Spot créé avec succès"
    else
      @spot = spot
      render 'new'
    end
  end

  def show
    @spot = Spot.find(params[:id])
  end

  def show_map
    @spot = Spot.find(params[:id])
  end

  def map
    @spots = Spot.all
  end

  def map_test
  end

  def geoloc
  end

  private

  def post_params
    params.require(:spot).permit(:name, :description, :image_url, :longitude)
  end

end

app/controllers/taxons_controller.rb
class TaxonsController < ApplicationController

  def new
    @taxon = Taxon.new
  end

  def index
    @taxons = Taxon.all
  end

  def create
    taxon = Taxon.new(post_params)
    if taxon.valid?
      taxon.save
      redirect_to taxon_path(taxon.id), success: "Taxon créé avec succès"
    else
      @taxon = taxon
      render 'new'
    end
  end

  def show
    @taxon = Taxon.find(params[:id])
  end

  private

  def post_params
    params.require(:taxon).permit(:common_noun, :family, :genus, :species)
  end

end

app/controllers/trees_controller.rb
class TreesController < ApplicationController

  def new
    @tree = Tree.new
  end

  def index
    @trees = Tree.all
  end

  def create
    tree = Tree.new(post_params)
    if tree.valid?
      tree.save
      redirect_to tree_path(tree.id), success: "Arbre créé avec succès"
    else
      @tree = tree
      render 'new'
    end
  end

  def show
    @tree = Tree.find(params[:id])
  end

  def map
    @trees = Tree.all
  end

  private

  def post_params
    params.require(:tree).permit(:name, :description, :latitude, :longitude, :taxon_id, :spot_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/helpers/taxons_helper.rb
module TaxonsHelper
end

app/helpers/trees_helper.rb
module TreesHelper
end

app/views/home/_about.html.erb
<section id="about" class="about-section text-center py-5 background-white">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-8 mx-auto">
        <h2 class="black-bean mb-4 text-uppercase">Le projet ?</h2>
        <h3 class="black-bean mb-4">Permettre aux gens de découvrir une espèce
          d'arbre en particulier grâce à un positionnement géographique des
          individus d'espèces. Tu veux savoir à quoi ressemble un oranger des
          osages et le voir en vrai ?
        </h3>
      </div>
    </div>
    <%= image_tag("", class: "img-fluid", alt: "") %>
  </div>
</section>

app/views/home/_about_perspective.html.erb
<section id="about" class="about-section text-center py-5 background-white">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-8 mx-auto">
        <h2 class="black-bean mb-4 text-uppercase">Fonctionnalités futures ?</h2>
        <h3 class="black-bean mb-4">
          Plein d'autres applications de cette base de données sont prévues !
        </h3>
      </div>
    </div>
    <%= image_tag("", class: "img-fluid", alt: "") %>
  </div>
</section>

app/views/home/_contact.html.erb
<section class="contact-section bg-black py-5 background-black-bean">
  <div class="container-fluid">
    <h2 class="text-white text-center mb-5">Contact</h2>
    <p class="text-white-50 text-center mb-5">Développement :
      <a href="https://github.com/Redcozmo" title="github" target="_blank" class=""><i class="fab fa-github"></i></a>
      <a href="https://www.linkedin.com/in/josselin-giffard-carlet-42330146/" title="linkedin" target="_blank" class=""><i class="fab fa-linkedin"></i></a>
    </p>
  </div>
</section>

app/views/home/_first_message.html.erb
<section id="" class="text-center py-5 background-black-bean">
  <div class="container-fluid">
    <h2 class="text-white-50">APPLICATION EN CONSTRUCTION</h2>
  </div>
</section>

app/views/home/_header.html.erb
<header class="container-fluid py-5 background-black-bean">
  <div class="container d-flex h-100 align-items-center">
    <div class="mx-auto text-center">
      <h1 class="mx-auto my-0 white text-uppercase">GEO TREE</h1>

      <div class="mx-auto mt-2 mb-5">
        <h2 class="hind-regular-white-1">Découvres les arbres autour de chez toi et contribues à diffuser la connaissance de ces communs.</h2>
        <a href="<%= trees_map_path %>" class="my-3 btn btn-success btn-lg">Commence l'exploration</a>
      </div>

      <em class="mx-auto white">Pour le moment, la carte dispose de ces communs :</em>
      <div class="text-white-50 mx-auto mt-2 mb-5">
        <p class="btn btn-success"><%= @spots.count %> jardins</p>
        <p class="btn btn-success"><%= @trees.count %> arbres</p>
        <p class="btn btn-success"><%= @taxons.count %> espèces</p>
      </div>
    </div>
  </div>
</header>

app/views/home/_newsletter.html.erb
<section id="signup" class="signup-section py-5 background-white">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-10 col-lg-8 mx-auto text-center black-bean">

        <i class="far fa-paper-plane fa-5x mb-2"></i>
        <h2 class="mb-5">Tu veux être informé(e) des avancées du projet ?</h2>

        <form class="form-inline d-flex">
          <input type="email" class="form-control flex-fill mr-0 mr-sm-2 mb-3 mb-sm-0" id="inputEmail" placeholder="Inscris ton adresse mail...">
          <button type="submit" class="btn btn-primary mx-auto">Je m'inscris !</button>
        </form>

      </div>
    </div>
  </div>
</section>

app/views/home/_project.html.erb
<section id="projects" class="projects-section py-5 background-black-bean">
  <div class="container-fluid">
    <h2 class="white text-center mb-4 text-uppercase">Comment enrichir la base et avoir des données fiables ?</h2>
    <div class="row align-items-center">

      <div class="w-100 my-auto text-lg-left col-lg-4">
        <i class="fas fa-users fa-5x mb-2 white"></i>
        <h4 class="text-white text-center">A toi de jouer !</h4>
        <p class="mb-0 text-white-50 text-center">Le projet se veut citoyen, à toi de
          référencer les arbres que tu rencontres.
          Quelques arbres sont déjà consultables sur la carte !
          Le projet se veut libre et ouvert, la base de données sera ainsi ouverte et contiendra aussi les données d'autres bases ouvertes comme OpenStreetMap.
        </p>
      </div>

      <div class="w-100 my-auto text-lg-left col-lg-4">
        <i class="fas fa-user-check fa-5x mb-2 white"></i>
        <h4 class="text-white text-center">Confirmation croisée</h4>
        <p class="mb-0 text-white-50 text-center">Afin d'être sûr de l'espèce des
          arbres référencés, plusieurs personnes vont confirmer ou ouvrir une discussions sur
          l'espèce d'un arbre.
        </p>
      </div>

      <div class="w-100 my-auto text-lg-left col-lg-4">
        <i class="fas fa-binoculars fa-5x mb-2 white"></i>
        <h4 class="text-white text-center">Référents natures</h4>
        <p class="mb-0 text-white-50 text-center">Tu es botaniste ou simplement fin
          connaisseur de la nature ? Tu pourras devenir référent par la
          qualité et la quantité du référencement d'arbres que tu feras.
        </p>
      </div>

    </div>

  </div>
</section>

app/views/home/_project_perspective.html.erb
<section id="projects" class="projects-section py-5 background-black-bean">
  <div class="container-fluid">
    <h2 class="white text-center mb-4 text-uppercase">A quoi d'autre peuvent servir ces données ?</h2>
    <div class="row align-items-center">

      <div class="w-100 my-auto text-lg-left col-lg-4">
        <!-- <i class="fas fa-users fa-5x mb-2 white"></i> -->
        <h4 class="text-white text-center">Bonus !</h4>
        <p class="mb-0 text-white-50 text-center">
          Contrairement à une opinion répandue, le Lorem Ipsum n'est pas
          simplement du texte aléatoire. Il trouve ses racines dans une oeuvre
          de la littérature latine classique datant de 45 av. J.-C., le rendant
          vieux de 2000 ans.
        </p>
      </div>

      <div class="w-100 my-auto text-lg-left col-lg-4">
        <!-- <i class="fas fa-user-check fa-5x mb-2 white"></i> -->
        <h4 class="text-white text-center">Waoooohh</h4>
        <p class="mb-0 text-white-50 text-center">
          Contrairement à une opinion répandue, le Lorem Ipsum n'est pas
          simplement du texte aléatoire. Il trouve ses racines dans une oeuvre
          de la littérature latine classique datant de 45 av. J.-C., le rendant
          vieux de 2000 ans.
        </p>
      </div>

      <div class="w-100 my-auto text-lg-left col-lg-4">
        <!-- <i class="fas fa-binoculars fa-5x mb-2 white"></i> -->
        <h4 class="text-white text-center">Mais encore !</h4>
        <p class="mb-0 text-white-50 text-center">
          Contrairement à une opinion répandue, le Lorem Ipsum n'est pas
          simplement du texte aléatoire. Il trouve ses racines dans une oeuvre
          de la littérature latine classique datant de 45 av. J.-C., le rendant
          vieux de 2000 ans.
        </p>
      </div>

    </div>

  </div>
</section>

app/views/home/index.html.erb
<!-- En construction -->
<%= render "home/first_message" %>

<!-- Header -->
<%= render "home/header" %>

<!-- About Section -->
<%= render "home/about" %>

<!-- Projects Section -->
<%= render "home/project" %>

<!-- About Section -->
<%= render "home/about_perspective" %>

<!-- Projects Section -->
<%= render "home/project_perspective" %>

<!-- Newsletter Section -->
<%= render "home/newsletter" %>

<!-- Contact Section -->
<%= render "home/contact" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="author" content="John Doe">
    <meta name="description" content="">
    <meta name="keywords" content="HTML,CSS,XML,JavaScript">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!--Bootstrap-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!--Leaflet CSS file-->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.4.0/dist/leaflet.css"
    integrity="sha512-puBpdR0798OZvTTbP4A8Ix/l+A4dHDD0DGqYW6RQ+9jxkRFclaxxQb/SJAWZfWAkuyeQUytO7+7N4QKrDh+drA=="
    crossorigin=""/>

    <!-- Leaflet JavaScript (necessary AFTER Leaflet's CSS) -->
    <script src="https://unpkg.com/leaflet@1.4.0/dist/leaflet.js"
    integrity="sha512-QVftwZFqvtRNi0ZyCtsznlKSWOStnDORoefr1enyq5mVL4tmKB3S/EnC3rRJcxCPavG10IcrVGSmPh6Qw5lwrg=="
    crossorigin=""></script>

    <!-- Title -->
    <title>GEO TREE</title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Custom fonts for the template -->
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  </head>

  <body id="page-top">
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="bg-black py-2 background-black-bean">
  <div class="container-fluid">
    <p class="text-white-50 text-center mb-5">Mentions légales</p>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md bg-dark navbar-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/"><span class="white">GEO TREE</span></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <div class="navbar-nav container d-flex justify-content-between">

        <div class="d-flex flex-row">

          <div class="nav-item dropdown">
            <a class="nav-link dropdown-toggle white text-uppercase" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Jardins
            </a>
            <div class="dropdown-menu white" aria-labelledby="navbarDropdown">
              <%= link_to 'Liste', spots_path, class: "dropdown-item" %>
              <%= link_to 'Carte', spots_map_path, class: "dropdown-item" %>
              <%= link_to 'Ajouter un spot', new_spot_path, class: "dropdown-item" %>
            </div>
          </div>

          <div class="nav-item dropdown">
            <a class="nav-link dropdown-toggle white text-uppercase" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Arbres
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to 'Liste', trees_path, class: "dropdown-item" %>
              <%= link_to 'Carte', trees_map_path, class: "dropdown-item" %>
              <%= link_to 'Ajouter un arbre', new_tree_path, class: "dropdown-item" %>
            </div>
          </div>

          <div class="nav-item dropdown">
            <a class="nav-link dropdown-toggle white text-uppercase" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Taxons
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to 'Liste', taxons_path, class: "dropdown-item" %>
              <%= link_to 'Ajouter un taxon', new_taxon_path, class: "dropdown-item" %>
            </div>
          </div>

          <div class="nav-item dropdown">
            <a class="nav-link dropdown-toggle white text-uppercase" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Cartes
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to 'Carte test', spots_map_test_path, class: "dropdown-item" %>
              <%= link_to 'Geoloc', spots_geoloc_path, class: "dropdown-item" %>
            </div>
          </div>

        </div>

        <div class="nav-item dropdown">

          <% if user_signed_in? %>
            <a class="nav-link dropdown-toggle white text-uppercase" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.email %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to 'Déconnexion', destroy_user_session_path, class: "dropdown-item", method: :delete %>
              <div class="dropdown-divider"></div>
              <%= link_to 'Profil', edit_user_registration_path, class: "dropdown-item" %>
            </div>

          <% else %>
            <a class="nav-link dropdown-toggle white text-uppercase" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Sign In / Sing Up
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to 'Connexion', new_user_session_path, class: "dropdown-item" %>
              <%= link_to 'Inscription', new_user_registration_path, class: "dropdown-item" %>
            </div>
          <% end %>

        </div>

      </div>
    </div>
  </div>
</nav>

app/views/spots/index.html.erb
<div class="container">
  <div class="text-center mt-4">
    <h1 class="lead">
      Liste des spots
    </h1>
  </div>
  <div class="row">
    <% @spots.each do |spot| %>
      <div class="col-12 col-md-6 col-lg-3">
      <!-- display all spots in a page -->
        <div class="card">
          <img class="card-img-top" src="<%= spot.image_url %>" alt="Unsplash">
          <div class="card-header">
            <h5 class="card-title mb-0"><%= spot.name %></h5>
          </div>
          <div class="card-body text-center">
            <div class="row">
              <div class="">
                <span class="badge badge-pill badge-info"><%= spot.trees.count %></span>
              </div>
              <div class="">
                <p>Arbres localisés</p>
              </div>
            </div>
            <div class="row">
              <div class="">
                <span class="badge badge-pill badge-info"><%= spot.taxa_count %></span>
              </div>
              <div class="">
                <p>Espèces identifiées</p>
              </div>
            </div>
            <p><%= link_to 'Détails', spot, class: "btn btn-info" %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/spots/show.html.erb
<!-- Spot display -->
<main class="main h-100 w-100">
	<div class="container h-100">
		<div class="row h-100">
			<div class="col-sm-10 col-md-8 col-lg-6 mx-auto d-table h-100">
				<div class="d-table-cell align-middle">

          <div class="text-center mt-4">
            <p class="h2"><%= link_to '<< Revenir à la liste', spots_path, class: "btn btn-primary" %></p>
          </div>
          <div class="text-center mt-4">
						<p class="lead">
							<%= @spot.name %>
						</p>
					</div>
          <!-- display all spots in a page -->
          <div>
            <ul class="nav nav-tabs" id="myTab" role="tablist">
              <li class="nav-item">
                <a class="nav-link active" id="photos-tab" data-toggle="tab" href="#photos" role="tab" aria-controls="photos"
                  aria-selected="true">Photos</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" id="especes-tab" data-toggle="tab" href="#especes" role="tab" aria-controls="especes"
                  aria-selected="false">Espèces</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" id="arbres-tab" data-toggle="tab" href="#arbres" role="tab" aria-controls="arbres"
                  aria-selected="false">Arbres</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" id="carte-tab" data-toggle="tab" href="#carte" role="tab" aria-controls="carte"
                  aria-selected="false">Carte</a>
              </li>
            </ul>
            <div class="tab-content" id="myTabContent">
              <div class="tab-pane fade show active" id="photos" role="tabpanel" aria-labelledby="photos-tab">
                <img class="card-img-top" src="<%= @spot.image_url %>" alt="Unsplash">
              </div>
              <div class="tab-pane fade" id="especes" role="tabpanel" aria-labelledby="especes-tab">
                <p>Sur ce spot il y a <%= @spot.taxa_count %> espèces identifiés.</p>
                <% @spot.taxa_array.sort_by { |word| word.mb_chars.normalize(:kd).gsub(/[^\x00-\x7F]/n,'').downcase.to_s }.each do |taxon| %>
                  <span class="badge badge-pill badge-info"><%= taxon %></span>
                <% end %>
              </div>
              <div class="tab-pane fade" id="arbres" role="tabpanel" aria-labelledby="arbres-tab">
                <p>Sur ce spot il y a <%= @spot.trees.count %> arbres localisés.</p>
              </div>
              <div class="tab-pane fade" id="carte" role="tabpanel" aria-labelledby="carte-tab">
                <p><%= link_to 'Carte', spots_show_map_path(@spot.id), class: "btn btn-primary" %></p>
              </div>
            </div>
          </div>
          <div class="text-center mt-4">
            <p class="h2"><%= link_to '<< Revenir à la liste', spots_path, class: "btn btn-primary" %></p>
          </div>
        </div>

      </div>
    </div>
  </div>
</main>

app/views/spots/show_map.html.erb
<p><%= link_to '<< Revenir au spot', spot_path %></p>

<p><%= link_to 'Add a tree on this spot', new_tree_path, class: "btn btn-primary" %></p>

<!-- Display on map -->
<div id="mapidone"></div>
<br>

<script type="text/javascript">
  // declaration objet
  var spotdisplay = L.map('mapidone').setView([45.777411, 4.855225], 13);
  L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
    attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
    maxZoom: 18,
    id: 'mapbox.streets',
    accessToken: '<%= Rails.application.credentials.dig(:mapbox, :secret_access_key) %>'
  }).addTo(spotdisplay);

  // One tree, one point/circle
	<% @spot.trees.each do |tree| %>
    // cercle
    var circle = L.circle([<%= tree.latitude.to_f %>, <%= tree.longitude.to_f %>], {
      color: 'green',
      fillColor: '#44e654',
      fillOpacity: 0.5,
      radius: 2
    }).addTo(spotdisplay);
    circle.bindPopup("<b><%= tree.name %></b>").openPopup();
	<% end %>
	// Recentrer la vue
	spotdisplay.setView([<%= @spot.latitude.to_f %>, <%= @spot.longitude.to_f %>], 16);
</script>

app/views/taxons/show.html.erb
tu as créé un taxon !!

app/views/trees/new.html.erb
<main class="main h-100 w-100">
	<div class="container h-100">
		<div class="row h-100">
			<div class="col-sm-10 col-md-8 col-lg-6 mx-auto d-table h-100">
				<div class="d-table-cell align-middle">

					<div class="text-center mt-4">
						<h1 class="h2">Add a tree on the spot</h1>
						<p class="lead">
							Merci de vouloir contribuer !
						</p>
					</div>

					<div class="card">
						<div class="card-body">
							<div class="m-sm-4">

                <%= form_for(@tree) do |f| %>

                <div class="form-group">
                  <%= f.label :name %> (optionnel)<br>
                  <%= f.text_field :name, class: "form-control form-control-lg", placeholder: "Enter name of spot" %>
                </div>

                <div class="form-group">
                  <%= f.label :description %> (optionnel)<br>
                  <%= f.text_area :description, class: "form-control form-control-lg", placeholder: "Description" %>
                </div>

                <div class="form-group">
                  <label for="taxon">Taxon</label>
                  <%= f.select :taxon_id, Taxon.pluck(:common_noun, :id), class: "form-control form-control-lg" %>
                </div>

                <div class="form-group">
                  <label for="spot">Spot</label>
                  <%= f.select :spot_id, Spot.pluck(:name, :id), class: "form-control form-control-lg" %>
                </div>

                <div class="form-group">
                  <%= link_to 'Add a new Taxon', new_taxon_path %>
                </div>

                <div class="form-group">
                  <%= f.label :latitude %> <%= f.label :longitude %><br>
                  <%= f.text_field :latitude, class: "form-control form-control-lg", placeholder: "Latitude" %>
                  <%= f.text_field :longitude, class: "form-control form-control-lg", placeholder: "Longitude" %>
                </div>

                <div id="mapgeoloc-add-tree"></div>

                <div class="text-center mt-3">
                  <%= f.submit %>
                </div>
                <% end %>
              </div>

						</div>
					</div>

				</div>
			</div>
		</div>
	</div>
</main>

<script type="text/javascript">
  // initialize the map object
  var mapgeoloc_add_tree = L.map('mapgeoloc-add-tree').fitWorld();

  L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
    attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
    maxZoom: 18,
    id: 'mapbox.streets',
		accessToken: '<%= Rails.application.credentials.dig(:mapbox, :secret_access_key) %>'
  }).addTo(mapgeoloc_add_tree);

  // zooming the map view to the detected location
  mapgeoloc_add_tree.locate({setView: true, maxZoom: 16});

  // locationfound and locationerror events
  function onLocationFound(e) {
    var radius = e.accuracy / 2;

    L.marker(e.latlng).addTo(mapgeoloc_add_tree)
        .bindPopup("You are within " + radius + " meters from this point").openPopup();

    L.circle(e.latlng, radius).addTo(mapgeoloc_add_tree);
  }

  mapgeoloc_add_tree.on('locationfound', onLocationFound);

  // message if the geolocation failed
  function onLocationError(e) {
    alert(e.message);
  }

  mapgeoloc_add_tree.on('locationerror', onLocationError);

</script>

app/views/trees/show.html.erb
tu as créé un arbre !!